name: Ubuntu CI

on:
  push:
  pull_request:

jobs:
  format:
    name: Format with clang-format
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      
      - name: echo GITHUB_REPOSITORY
        run: echo ${GITHUB_REPOSITORY}
        
      - name: clone (pull_request)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git clone -b "${GITHUB_HEAD_REF#refs/heads/}" https://github.com/${{ github.event.pull_request.head.repo.full_name }}

      - name: clone (push)
        if: ${{ github.event_name == 'push' }}
        run: |
          git clone -b "${GITHUB_REF#refs/heads/}" https://github.com/${GITHUB_REPOSITORY}

      - name: show pwd
        run: pwd

      - name: show list
        run: ls -a
